### ISSUE TITLE
I can't seem to get this working when using TypeScript

### ISSUE THREAD

**Issue by RebeccaStevens** [unassert-js/rollup-plugin-unassert#4]
I did some testing and it all work with JS but not with TS.
Any idea how I can get it to work with TS?

(I tried setting `include: ["**/*.ts"]`)

**Comment by mourner** [comment]
Sure! Thanks for the contributions @RebeccaStevens. Also pushed https://github.com/unassert-js/rollup-plugin-unassert/commit/cc2cb65aa55de85e41db5a062d7ea790f02ac199 with some deps updates.

@IvanSanchez looks like you're the only owner in NPM — can you publish the latest commit (v0.4.0), and maybe add a few more people as NPM owners just in case?

**Comment by RebeccaStevens** [comment]
I've got everything work using those latest changes and with a custom version of unassert that updates its dependency updates.

**Comment by mourner** [comment]
@IvanSanchez gentle reminder.

**Comment by mourner** [comment]
Published v0.4.0 🎉 Thanks Ivan!
